# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/noah/Projects/SIR-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/noah/Projects/SIR-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noah/Projects/SIR-Engine/CMakeFiles /home/noah/Projects/SIR-Engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noah/Projects/SIR-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SIREngineApplication

# Build rule for target.
SIREngineApplication: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SIREngineApplication
.PHONY : SIREngineApplication

# fast build rule for target.
SIREngineApplication/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/build
.PHONY : SIREngineApplication/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

Engine/Core/Application/GenericPlatform/GenericApplication.o: Engine/Core/Application/GenericPlatform/GenericApplication.cpp.o
.PHONY : Engine/Core/Application/GenericPlatform/GenericApplication.o

# target to build an object file
Engine/Core/Application/GenericPlatform/GenericApplication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/GenericPlatform/GenericApplication.cpp.o
.PHONY : Engine/Core/Application/GenericPlatform/GenericApplication.cpp.o

Engine/Core/Application/GenericPlatform/GenericApplication.i: Engine/Core/Application/GenericPlatform/GenericApplication.cpp.i
.PHONY : Engine/Core/Application/GenericPlatform/GenericApplication.i

# target to preprocess a source file
Engine/Core/Application/GenericPlatform/GenericApplication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/GenericPlatform/GenericApplication.cpp.i
.PHONY : Engine/Core/Application/GenericPlatform/GenericApplication.cpp.i

Engine/Core/Application/GenericPlatform/GenericApplication.s: Engine/Core/Application/GenericPlatform/GenericApplication.cpp.s
.PHONY : Engine/Core/Application/GenericPlatform/GenericApplication.s

# target to generate assembly for a file
Engine/Core/Application/GenericPlatform/GenericApplication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/GenericPlatform/GenericApplication.cpp.s
.PHONY : Engine/Core/Application/GenericPlatform/GenericApplication.cpp.s

Engine/Core/Application/Posix/PosixApplication.o: Engine/Core/Application/Posix/PosixApplication.cpp.o
.PHONY : Engine/Core/Application/Posix/PosixApplication.o

# target to build an object file
Engine/Core/Application/Posix/PosixApplication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/Posix/PosixApplication.cpp.o
.PHONY : Engine/Core/Application/Posix/PosixApplication.cpp.o

Engine/Core/Application/Posix/PosixApplication.i: Engine/Core/Application/Posix/PosixApplication.cpp.i
.PHONY : Engine/Core/Application/Posix/PosixApplication.i

# target to preprocess a source file
Engine/Core/Application/Posix/PosixApplication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/Posix/PosixApplication.cpp.i
.PHONY : Engine/Core/Application/Posix/PosixApplication.cpp.i

Engine/Core/Application/Posix/PosixApplication.s: Engine/Core/Application/Posix/PosixApplication.cpp.s
.PHONY : Engine/Core/Application/Posix/PosixApplication.s

# target to generate assembly for a file
Engine/Core/Application/Posix/PosixApplication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/Posix/PosixApplication.cpp.s
.PHONY : Engine/Core/Application/Posix/PosixApplication.cpp.s

Engine/Core/Application/Posix/PosixCrashHandler.o: Engine/Core/Application/Posix/PosixCrashHandler.cpp.o
.PHONY : Engine/Core/Application/Posix/PosixCrashHandler.o

# target to build an object file
Engine/Core/Application/Posix/PosixCrashHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/Posix/PosixCrashHandler.cpp.o
.PHONY : Engine/Core/Application/Posix/PosixCrashHandler.cpp.o

Engine/Core/Application/Posix/PosixCrashHandler.i: Engine/Core/Application/Posix/PosixCrashHandler.cpp.i
.PHONY : Engine/Core/Application/Posix/PosixCrashHandler.i

# target to preprocess a source file
Engine/Core/Application/Posix/PosixCrashHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/Posix/PosixCrashHandler.cpp.i
.PHONY : Engine/Core/Application/Posix/PosixCrashHandler.cpp.i

Engine/Core/Application/Posix/PosixCrashHandler.s: Engine/Core/Application/Posix/PosixCrashHandler.cpp.s
.PHONY : Engine/Core/Application/Posix/PosixCrashHandler.s

# target to generate assembly for a file
Engine/Core/Application/Posix/PosixCrashHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Application/Posix/PosixCrashHandler.cpp.s
.PHONY : Engine/Core/Application/Posix/PosixCrashHandler.cpp.s

Engine/Core/ConsoleManager.o: Engine/Core/ConsoleManager.cpp.o
.PHONY : Engine/Core/ConsoleManager.o

# target to build an object file
Engine/Core/ConsoleManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/ConsoleManager.cpp.o
.PHONY : Engine/Core/ConsoleManager.cpp.o

Engine/Core/ConsoleManager.i: Engine/Core/ConsoleManager.cpp.i
.PHONY : Engine/Core/ConsoleManager.i

# target to preprocess a source file
Engine/Core/ConsoleManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/ConsoleManager.cpp.i
.PHONY : Engine/Core/ConsoleManager.cpp.i

Engine/Core/ConsoleManager.s: Engine/Core/ConsoleManager.cpp.s
.PHONY : Engine/Core/ConsoleManager.s

# target to generate assembly for a file
Engine/Core/ConsoleManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/ConsoleManager.cpp.s
.PHONY : Engine/Core/ConsoleManager.cpp.s

Engine/Core/Events/EventManager.o: Engine/Core/Events/EventManager.cpp.o
.PHONY : Engine/Core/Events/EventManager.o

# target to build an object file
Engine/Core/Events/EventManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Events/EventManager.cpp.o
.PHONY : Engine/Core/Events/EventManager.cpp.o

Engine/Core/Events/EventManager.i: Engine/Core/Events/EventManager.cpp.i
.PHONY : Engine/Core/Events/EventManager.i

# target to preprocess a source file
Engine/Core/Events/EventManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Events/EventManager.cpp.i
.PHONY : Engine/Core/Events/EventManager.cpp.i

Engine/Core/Events/EventManager.s: Engine/Core/Events/EventManager.cpp.s
.PHONY : Engine/Core/Events/EventManager.s

# target to generate assembly for a file
Engine/Core/Events/EventManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Events/EventManager.cpp.s
.PHONY : Engine/Core/Events/EventManager.cpp.s

Engine/Core/Events/KeyEvent.o: Engine/Core/Events/KeyEvent.cpp.o
.PHONY : Engine/Core/Events/KeyEvent.o

# target to build an object file
Engine/Core/Events/KeyEvent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Events/KeyEvent.cpp.o
.PHONY : Engine/Core/Events/KeyEvent.cpp.o

Engine/Core/Events/KeyEvent.i: Engine/Core/Events/KeyEvent.cpp.i
.PHONY : Engine/Core/Events/KeyEvent.i

# target to preprocess a source file
Engine/Core/Events/KeyEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Events/KeyEvent.cpp.i
.PHONY : Engine/Core/Events/KeyEvent.cpp.i

Engine/Core/Events/KeyEvent.s: Engine/Core/Events/KeyEvent.cpp.s
.PHONY : Engine/Core/Events/KeyEvent.s

# target to generate assembly for a file
Engine/Core/Events/KeyEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Events/KeyEvent.cpp.s
.PHONY : Engine/Core/Events/KeyEvent.cpp.s

Engine/Core/FileSystem/FileCache.o: Engine/Core/FileSystem/FileCache.cpp.o
.PHONY : Engine/Core/FileSystem/FileCache.o

# target to build an object file
Engine/Core/FileSystem/FileCache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/FileSystem/FileCache.cpp.o
.PHONY : Engine/Core/FileSystem/FileCache.cpp.o

Engine/Core/FileSystem/FileCache.i: Engine/Core/FileSystem/FileCache.cpp.i
.PHONY : Engine/Core/FileSystem/FileCache.i

# target to preprocess a source file
Engine/Core/FileSystem/FileCache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/FileSystem/FileCache.cpp.i
.PHONY : Engine/Core/FileSystem/FileCache.cpp.i

Engine/Core/FileSystem/FileCache.s: Engine/Core/FileSystem/FileCache.cpp.s
.PHONY : Engine/Core/FileSystem/FileCache.s

# target to generate assembly for a file
Engine/Core/FileSystem/FileCache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/FileSystem/FileCache.cpp.s
.PHONY : Engine/Core/FileSystem/FileCache.cpp.s

Engine/Core/FileSystem/FileSystem.o: Engine/Core/FileSystem/FileSystem.cpp.o
.PHONY : Engine/Core/FileSystem/FileSystem.o

# target to build an object file
Engine/Core/FileSystem/FileSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/FileSystem/FileSystem.cpp.o
.PHONY : Engine/Core/FileSystem/FileSystem.cpp.o

Engine/Core/FileSystem/FileSystem.i: Engine/Core/FileSystem/FileSystem.cpp.i
.PHONY : Engine/Core/FileSystem/FileSystem.i

# target to preprocess a source file
Engine/Core/FileSystem/FileSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/FileSystem/FileSystem.cpp.i
.PHONY : Engine/Core/FileSystem/FileSystem.cpp.i

Engine/Core/FileSystem/FileSystem.s: Engine/Core/FileSystem/FileSystem.cpp.s
.PHONY : Engine/Core/FileSystem/FileSystem.s

# target to generate assembly for a file
Engine/Core/FileSystem/FileSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/FileSystem/FileSystem.cpp.s
.PHONY : Engine/Core/FileSystem/FileSystem.cpp.s

Engine/Core/Input/InputManager.o: Engine/Core/Input/InputManager.cpp.o
.PHONY : Engine/Core/Input/InputManager.o

# target to build an object file
Engine/Core/Input/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Input/InputManager.cpp.o
.PHONY : Engine/Core/Input/InputManager.cpp.o

Engine/Core/Input/InputManager.i: Engine/Core/Input/InputManager.cpp.i
.PHONY : Engine/Core/Input/InputManager.i

# target to preprocess a source file
Engine/Core/Input/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Input/InputManager.cpp.i
.PHONY : Engine/Core/Input/InputManager.cpp.i

Engine/Core/Input/InputManager.s: Engine/Core/Input/InputManager.cpp.s
.PHONY : Engine/Core/Input/InputManager.s

# target to generate assembly for a file
Engine/Core/Input/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Input/InputManager.cpp.s
.PHONY : Engine/Core/Input/InputManager.cpp.s

Engine/Core/Logging/Logger.o: Engine/Core/Logging/Logger.cpp.o
.PHONY : Engine/Core/Logging/Logger.o

# target to build an object file
Engine/Core/Logging/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Logging/Logger.cpp.o
.PHONY : Engine/Core/Logging/Logger.cpp.o

Engine/Core/Logging/Logger.i: Engine/Core/Logging/Logger.cpp.i
.PHONY : Engine/Core/Logging/Logger.i

# target to preprocess a source file
Engine/Core/Logging/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Logging/Logger.cpp.i
.PHONY : Engine/Core/Logging/Logger.cpp.i

Engine/Core/Logging/Logger.s: Engine/Core/Logging/Logger.cpp.s
.PHONY : Engine/Core/Logging/Logger.s

# target to generate assembly for a file
Engine/Core/Logging/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Logging/Logger.cpp.s
.PHONY : Engine/Core/Logging/Logger.cpp.s

Engine/Core/Serialization/Ini/IniReader.o: Engine/Core/Serialization/Ini/IniReader.cpp.o
.PHONY : Engine/Core/Serialization/Ini/IniReader.o

# target to build an object file
Engine/Core/Serialization/Ini/IniReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/IniReader.cpp.o
.PHONY : Engine/Core/Serialization/Ini/IniReader.cpp.o

Engine/Core/Serialization/Ini/IniReader.i: Engine/Core/Serialization/Ini/IniReader.cpp.i
.PHONY : Engine/Core/Serialization/Ini/IniReader.i

# target to preprocess a source file
Engine/Core/Serialization/Ini/IniReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/IniReader.cpp.i
.PHONY : Engine/Core/Serialization/Ini/IniReader.cpp.i

Engine/Core/Serialization/Ini/IniReader.s: Engine/Core/Serialization/Ini/IniReader.cpp.s
.PHONY : Engine/Core/Serialization/Ini/IniReader.s

# target to generate assembly for a file
Engine/Core/Serialization/Ini/IniReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/IniReader.cpp.s
.PHONY : Engine/Core/Serialization/Ini/IniReader.cpp.s

Engine/Core/Serialization/Ini/IniWriter.o: Engine/Core/Serialization/Ini/IniWriter.cpp.o
.PHONY : Engine/Core/Serialization/Ini/IniWriter.o

# target to build an object file
Engine/Core/Serialization/Ini/IniWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/IniWriter.cpp.o
.PHONY : Engine/Core/Serialization/Ini/IniWriter.cpp.o

Engine/Core/Serialization/Ini/IniWriter.i: Engine/Core/Serialization/Ini/IniWriter.cpp.i
.PHONY : Engine/Core/Serialization/Ini/IniWriter.i

# target to preprocess a source file
Engine/Core/Serialization/Ini/IniWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/IniWriter.cpp.i
.PHONY : Engine/Core/Serialization/Ini/IniWriter.cpp.i

Engine/Core/Serialization/Ini/IniWriter.s: Engine/Core/Serialization/Ini/IniWriter.cpp.s
.PHONY : Engine/Core/Serialization/Ini/IniWriter.s

# target to generate assembly for a file
Engine/Core/Serialization/Ini/IniWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/IniWriter.cpp.s
.PHONY : Engine/Core/Serialization/Ini/IniWriter.cpp.s

Engine/Core/Serialization/Ini/ini.o: Engine/Core/Serialization/Ini/ini.cpp.o
.PHONY : Engine/Core/Serialization/Ini/ini.o

# target to build an object file
Engine/Core/Serialization/Ini/ini.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/ini.cpp.o
.PHONY : Engine/Core/Serialization/Ini/ini.cpp.o

Engine/Core/Serialization/Ini/ini.i: Engine/Core/Serialization/Ini/ini.cpp.i
.PHONY : Engine/Core/Serialization/Ini/ini.i

# target to preprocess a source file
Engine/Core/Serialization/Ini/ini.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/ini.cpp.i
.PHONY : Engine/Core/Serialization/Ini/ini.cpp.i

Engine/Core/Serialization/Ini/ini.s: Engine/Core/Serialization/Ini/ini.cpp.s
.PHONY : Engine/Core/Serialization/Ini/ini.s

# target to generate assembly for a file
Engine/Core/Serialization/Ini/ini.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/Ini/ini.cpp.s
.PHONY : Engine/Core/Serialization/Ini/ini.cpp.s

Engine/Core/Serialization/JSon/JsonCache.o: Engine/Core/Serialization/JSon/JsonCache.cpp.o
.PHONY : Engine/Core/Serialization/JSon/JsonCache.o

# target to build an object file
Engine/Core/Serialization/JSon/JsonCache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/JSon/JsonCache.cpp.o
.PHONY : Engine/Core/Serialization/JSon/JsonCache.cpp.o

Engine/Core/Serialization/JSon/JsonCache.i: Engine/Core/Serialization/JSon/JsonCache.cpp.i
.PHONY : Engine/Core/Serialization/JSon/JsonCache.i

# target to preprocess a source file
Engine/Core/Serialization/JSon/JsonCache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/JSon/JsonCache.cpp.i
.PHONY : Engine/Core/Serialization/JSon/JsonCache.cpp.i

Engine/Core/Serialization/JSon/JsonCache.s: Engine/Core/Serialization/JSon/JsonCache.cpp.s
.PHONY : Engine/Core/Serialization/JSon/JsonCache.s

# target to generate assembly for a file
Engine/Core/Serialization/JSon/JsonCache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/JSon/JsonCache.cpp.s
.PHONY : Engine/Core/Serialization/JSon/JsonCache.cpp.s

Engine/Core/Serialization/TBon/TBonSerializer.o: Engine/Core/Serialization/TBon/TBonSerializer.cpp.o
.PHONY : Engine/Core/Serialization/TBon/TBonSerializer.o

# target to build an object file
Engine/Core/Serialization/TBon/TBonSerializer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/TBon/TBonSerializer.cpp.o
.PHONY : Engine/Core/Serialization/TBon/TBonSerializer.cpp.o

Engine/Core/Serialization/TBon/TBonSerializer.i: Engine/Core/Serialization/TBon/TBonSerializer.cpp.i
.PHONY : Engine/Core/Serialization/TBon/TBonSerializer.i

# target to preprocess a source file
Engine/Core/Serialization/TBon/TBonSerializer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/TBon/TBonSerializer.cpp.i
.PHONY : Engine/Core/Serialization/TBon/TBonSerializer.cpp.i

Engine/Core/Serialization/TBon/TBonSerializer.s: Engine/Core/Serialization/TBon/TBonSerializer.cpp.s
.PHONY : Engine/Core/Serialization/TBon/TBonSerializer.s

# target to generate assembly for a file
Engine/Core/Serialization/TBon/TBonSerializer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Serialization/TBon/TBonSerializer.cpp.s
.PHONY : Engine/Core/Serialization/TBon/TBonSerializer.cpp.s

Engine/Core/SmMalloc/smmalloc.o: Engine/Core/SmMalloc/smmalloc.cpp.o
.PHONY : Engine/Core/SmMalloc/smmalloc.o

# target to build an object file
Engine/Core/SmMalloc/smmalloc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc.cpp.o
.PHONY : Engine/Core/SmMalloc/smmalloc.cpp.o

Engine/Core/SmMalloc/smmalloc.i: Engine/Core/SmMalloc/smmalloc.cpp.i
.PHONY : Engine/Core/SmMalloc/smmalloc.i

# target to preprocess a source file
Engine/Core/SmMalloc/smmalloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc.cpp.i
.PHONY : Engine/Core/SmMalloc/smmalloc.cpp.i

Engine/Core/SmMalloc/smmalloc.s: Engine/Core/SmMalloc/smmalloc.cpp.s
.PHONY : Engine/Core/SmMalloc/smmalloc.s

# target to generate assembly for a file
Engine/Core/SmMalloc/smmalloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc.cpp.s
.PHONY : Engine/Core/SmMalloc/smmalloc.cpp.s

Engine/Core/SmMalloc/smmalloc_generic.o: Engine/Core/SmMalloc/smmalloc_generic.cpp.o
.PHONY : Engine/Core/SmMalloc/smmalloc_generic.o

# target to build an object file
Engine/Core/SmMalloc/smmalloc_generic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc_generic.cpp.o
.PHONY : Engine/Core/SmMalloc/smmalloc_generic.cpp.o

Engine/Core/SmMalloc/smmalloc_generic.i: Engine/Core/SmMalloc/smmalloc_generic.cpp.i
.PHONY : Engine/Core/SmMalloc/smmalloc_generic.i

# target to preprocess a source file
Engine/Core/SmMalloc/smmalloc_generic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc_generic.cpp.i
.PHONY : Engine/Core/SmMalloc/smmalloc_generic.cpp.i

Engine/Core/SmMalloc/smmalloc_generic.s: Engine/Core/SmMalloc/smmalloc_generic.cpp.s
.PHONY : Engine/Core/SmMalloc/smmalloc_generic.s

# target to generate assembly for a file
Engine/Core/SmMalloc/smmalloc_generic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc_generic.cpp.s
.PHONY : Engine/Core/SmMalloc/smmalloc_generic.cpp.s

Engine/Core/SmMalloc/smmalloc_tls.o: Engine/Core/SmMalloc/smmalloc_tls.cpp.o
.PHONY : Engine/Core/SmMalloc/smmalloc_tls.o

# target to build an object file
Engine/Core/SmMalloc/smmalloc_tls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc_tls.cpp.o
.PHONY : Engine/Core/SmMalloc/smmalloc_tls.cpp.o

Engine/Core/SmMalloc/smmalloc_tls.i: Engine/Core/SmMalloc/smmalloc_tls.cpp.i
.PHONY : Engine/Core/SmMalloc/smmalloc_tls.i

# target to preprocess a source file
Engine/Core/SmMalloc/smmalloc_tls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc_tls.cpp.i
.PHONY : Engine/Core/SmMalloc/smmalloc_tls.cpp.i

Engine/Core/SmMalloc/smmalloc_tls.s: Engine/Core/SmMalloc/smmalloc_tls.cpp.s
.PHONY : Engine/Core/SmMalloc/smmalloc_tls.s

# target to generate assembly for a file
Engine/Core/SmMalloc/smmalloc_tls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/SmMalloc/smmalloc_tls.cpp.s
.PHONY : Engine/Core/SmMalloc/smmalloc_tls.cpp.s

Engine/Core/Util.o: Engine/Core/Util.cpp.o
.PHONY : Engine/Core/Util.o

# target to build an object file
Engine/Core/Util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Util.cpp.o
.PHONY : Engine/Core/Util.cpp.o

Engine/Core/Util.i: Engine/Core/Util.cpp.i
.PHONY : Engine/Core/Util.i

# target to preprocess a source file
Engine/Core/Util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Util.cpp.i
.PHONY : Engine/Core/Util.cpp.i

Engine/Core/Util.s: Engine/Core/Util.cpp.s
.PHONY : Engine/Core/Util.s

# target to generate assembly for a file
Engine/Core/Util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Core/Util.cpp.s
.PHONY : Engine/Core/Util.cpp.s

Engine/Memory/Allocators/SlabAllocator.o: Engine/Memory/Allocators/SlabAllocator.cpp.o
.PHONY : Engine/Memory/Allocators/SlabAllocator.o

# target to build an object file
Engine/Memory/Allocators/SlabAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Allocators/SlabAllocator.cpp.o
.PHONY : Engine/Memory/Allocators/SlabAllocator.cpp.o

Engine/Memory/Allocators/SlabAllocator.i: Engine/Memory/Allocators/SlabAllocator.cpp.i
.PHONY : Engine/Memory/Allocators/SlabAllocator.i

# target to preprocess a source file
Engine/Memory/Allocators/SlabAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Allocators/SlabAllocator.cpp.i
.PHONY : Engine/Memory/Allocators/SlabAllocator.cpp.i

Engine/Memory/Allocators/SlabAllocator.s: Engine/Memory/Allocators/SlabAllocator.cpp.s
.PHONY : Engine/Memory/Allocators/SlabAllocator.s

# target to generate assembly for a file
Engine/Memory/Allocators/SlabAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Allocators/SlabAllocator.cpp.s
.PHONY : Engine/Memory/Allocators/SlabAllocator.cpp.s

Engine/Memory/Allocators/VirtualStackAllocator.o: Engine/Memory/Allocators/VirtualStackAllocator.cpp.o
.PHONY : Engine/Memory/Allocators/VirtualStackAllocator.o

# target to build an object file
Engine/Memory/Allocators/VirtualStackAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Allocators/VirtualStackAllocator.cpp.o
.PHONY : Engine/Memory/Allocators/VirtualStackAllocator.cpp.o

Engine/Memory/Allocators/VirtualStackAllocator.i: Engine/Memory/Allocators/VirtualStackAllocator.cpp.i
.PHONY : Engine/Memory/Allocators/VirtualStackAllocator.i

# target to preprocess a source file
Engine/Memory/Allocators/VirtualStackAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Allocators/VirtualStackAllocator.cpp.i
.PHONY : Engine/Memory/Allocators/VirtualStackAllocator.cpp.i

Engine/Memory/Allocators/VirtualStackAllocator.s: Engine/Memory/Allocators/VirtualStackAllocator.cpp.s
.PHONY : Engine/Memory/Allocators/VirtualStackAllocator.s

# target to generate assembly for a file
Engine/Memory/Allocators/VirtualStackAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Allocators/VirtualStackAllocator.cpp.s
.PHONY : Engine/Memory/Allocators/VirtualStackAllocator.cpp.s

Engine/Memory/Backend/TagArenaAllocator.o: Engine/Memory/Backend/TagArenaAllocator.cpp.o
.PHONY : Engine/Memory/Backend/TagArenaAllocator.o

# target to build an object file
Engine/Memory/Backend/TagArenaAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Backend/TagArenaAllocator.cpp.o
.PHONY : Engine/Memory/Backend/TagArenaAllocator.cpp.o

Engine/Memory/Backend/TagArenaAllocator.i: Engine/Memory/Backend/TagArenaAllocator.cpp.i
.PHONY : Engine/Memory/Backend/TagArenaAllocator.i

# target to preprocess a source file
Engine/Memory/Backend/TagArenaAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Backend/TagArenaAllocator.cpp.i
.PHONY : Engine/Memory/Backend/TagArenaAllocator.cpp.i

Engine/Memory/Backend/TagArenaAllocator.s: Engine/Memory/Backend/TagArenaAllocator.cpp.s
.PHONY : Engine/Memory/Backend/TagArenaAllocator.s

# target to generate assembly for a file
Engine/Memory/Backend/TagArenaAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Backend/TagArenaAllocator.cpp.s
.PHONY : Engine/Memory/Backend/TagArenaAllocator.cpp.s

Engine/Memory/Memory.o: Engine/Memory/Memory.cpp.o
.PHONY : Engine/Memory/Memory.o

# target to build an object file
Engine/Memory/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Memory.cpp.o
.PHONY : Engine/Memory/Memory.cpp.o

Engine/Memory/Memory.i: Engine/Memory/Memory.cpp.i
.PHONY : Engine/Memory/Memory.i

# target to preprocess a source file
Engine/Memory/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Memory.cpp.i
.PHONY : Engine/Memory/Memory.cpp.i

Engine/Memory/Memory.s: Engine/Memory/Memory.cpp.s
.PHONY : Engine/Memory/Memory.s

# target to generate assembly for a file
Engine/Memory/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/Memory/Memory.cpp.s
.PHONY : Engine/Memory/Memory.cpp.s

Engine/RenderLib/Backend/ImageLib/LoadPNG.o: Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.o
.PHONY : Engine/RenderLib/Backend/ImageLib/LoadPNG.o

# target to build an object file
Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.o
.PHONY : Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.o

Engine/RenderLib/Backend/ImageLib/LoadPNG.i: Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.i
.PHONY : Engine/RenderLib/Backend/ImageLib/LoadPNG.i

# target to preprocess a source file
Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.i
.PHONY : Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.i

Engine/RenderLib/Backend/ImageLib/LoadPNG.s: Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.s
.PHONY : Engine/RenderLib/Backend/ImageLib/LoadPNG.s

# target to generate assembly for a file
Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.s
.PHONY : Engine/RenderLib/Backend/ImageLib/LoadPNG.cpp.s

Engine/RenderLib/Backend/ImageLoader.o: Engine/RenderLib/Backend/ImageLoader.cpp.o
.PHONY : Engine/RenderLib/Backend/ImageLoader.o

# target to build an object file
Engine/RenderLib/Backend/ImageLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/ImageLoader.cpp.o
.PHONY : Engine/RenderLib/Backend/ImageLoader.cpp.o

Engine/RenderLib/Backend/ImageLoader.i: Engine/RenderLib/Backend/ImageLoader.cpp.i
.PHONY : Engine/RenderLib/Backend/ImageLoader.i

# target to preprocess a source file
Engine/RenderLib/Backend/ImageLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/ImageLoader.cpp.i
.PHONY : Engine/RenderLib/Backend/ImageLoader.cpp.i

Engine/RenderLib/Backend/ImageLoader.s: Engine/RenderLib/Backend/ImageLoader.cpp.s
.PHONY : Engine/RenderLib/Backend/ImageLoader.s

# target to generate assembly for a file
Engine/RenderLib/Backend/ImageLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/ImageLoader.cpp.s
.PHONY : Engine/RenderLib/Backend/ImageLoader.cpp.s

Engine/RenderLib/Backend/OpenGL/GLBuffer.o: Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLBuffer.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.o

Engine/RenderLib/Backend/OpenGL/GLBuffer.i: Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLBuffer.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.i

Engine/RenderLib/Backend/OpenGL/GLBuffer.s: Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLBuffer.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLBuffer.cpp.s

Engine/RenderLib/Backend/OpenGL/GLContext.o: Engine/RenderLib/Backend/OpenGL/GLContext.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLContext.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLContext.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLContext.cpp.o

Engine/RenderLib/Backend/OpenGL/GLContext.i: Engine/RenderLib/Backend/OpenGL/GLContext.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLContext.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLContext.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLContext.cpp.i

Engine/RenderLib/Backend/OpenGL/GLContext.s: Engine/RenderLib/Backend/OpenGL/GLContext.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLContext.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLContext.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLContext.cpp.s

Engine/RenderLib/Backend/OpenGL/GLFramebuffer.o: Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLFramebuffer.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.o

Engine/RenderLib/Backend/OpenGL/GLFramebuffer.i: Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLFramebuffer.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.i

Engine/RenderLib/Backend/OpenGL/GLFramebuffer.s: Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLFramebuffer.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLFramebuffer.cpp.s

Engine/RenderLib/Backend/OpenGL/GLProcs.o: Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProcs.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.o

Engine/RenderLib/Backend/OpenGL/GLProcs.i: Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProcs.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.i

Engine/RenderLib/Backend/OpenGL/GLProcs.s: Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProcs.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProcs.cpp.s

Engine/RenderLib/Backend/OpenGL/GLProgram.o: Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProgram.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.o

Engine/RenderLib/Backend/OpenGL/GLProgram.i: Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProgram.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.i

Engine/RenderLib/Backend/OpenGL/GLProgram.s: Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProgram.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLProgram.cpp.s

Engine/RenderLib/Backend/OpenGL/GLShader.o: Engine/RenderLib/Backend/OpenGL/GLShader.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShader.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShader.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShader.cpp.o

Engine/RenderLib/Backend/OpenGL/GLShader.i: Engine/RenderLib/Backend/OpenGL/GLShader.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShader.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShader.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShader.cpp.i

Engine/RenderLib/Backend/OpenGL/GLShader.s: Engine/RenderLib/Backend/OpenGL/GLShader.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShader.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShader.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShader.cpp.s

Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.o: Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.o

Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.i: Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.i

Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.s: Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.cpp.s

Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.o: Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.o

Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.i: Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.i

Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.s: Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.cpp.s

Engine/RenderLib/Backend/OpenGL/GLTexture.o: Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLTexture.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.o

Engine/RenderLib/Backend/OpenGL/GLTexture.i: Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLTexture.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.i

Engine/RenderLib/Backend/OpenGL/GLTexture.s: Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLTexture.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLTexture.cpp.s

Engine/RenderLib/Backend/OpenGL/GLVertexArray.o: Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLVertexArray.o

# target to build an object file
Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.o
.PHONY : Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.o

Engine/RenderLib/Backend/OpenGL/GLVertexArray.i: Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLVertexArray.i

# target to preprocess a source file
Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.i
.PHONY : Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.i

Engine/RenderLib/Backend/OpenGL/GLVertexArray.s: Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLVertexArray.s

# target to generate assembly for a file
Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.s
.PHONY : Engine/RenderLib/Backend/OpenGL/GLVertexArray.cpp.s

Engine/RenderLib/Backend/RenderContext.o: Engine/RenderLib/Backend/RenderContext.cpp.o
.PHONY : Engine/RenderLib/Backend/RenderContext.o

# target to build an object file
Engine/RenderLib/Backend/RenderContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/RenderContext.cpp.o
.PHONY : Engine/RenderLib/Backend/RenderContext.cpp.o

Engine/RenderLib/Backend/RenderContext.i: Engine/RenderLib/Backend/RenderContext.cpp.i
.PHONY : Engine/RenderLib/Backend/RenderContext.i

# target to preprocess a source file
Engine/RenderLib/Backend/RenderContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/RenderContext.cpp.i
.PHONY : Engine/RenderLib/Backend/RenderContext.cpp.i

Engine/RenderLib/Backend/RenderContext.s: Engine/RenderLib/Backend/RenderContext.cpp.s
.PHONY : Engine/RenderLib/Backend/RenderContext.s

# target to generate assembly for a file
Engine/RenderLib/Backend/RenderContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/RenderContext.cpp.s
.PHONY : Engine/RenderLib/Backend/RenderContext.cpp.s

Engine/RenderLib/Backend/RenderShaderPipeline.o: Engine/RenderLib/Backend/RenderShaderPipeline.cpp.o
.PHONY : Engine/RenderLib/Backend/RenderShaderPipeline.o

# target to build an object file
Engine/RenderLib/Backend/RenderShaderPipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/RenderShaderPipeline.cpp.o
.PHONY : Engine/RenderLib/Backend/RenderShaderPipeline.cpp.o

Engine/RenderLib/Backend/RenderShaderPipeline.i: Engine/RenderLib/Backend/RenderShaderPipeline.cpp.i
.PHONY : Engine/RenderLib/Backend/RenderShaderPipeline.i

# target to preprocess a source file
Engine/RenderLib/Backend/RenderShaderPipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/RenderShaderPipeline.cpp.i
.PHONY : Engine/RenderLib/Backend/RenderShaderPipeline.cpp.i

Engine/RenderLib/Backend/RenderShaderPipeline.s: Engine/RenderLib/Backend/RenderShaderPipeline.cpp.s
.PHONY : Engine/RenderLib/Backend/RenderShaderPipeline.s

# target to generate assembly for a file
Engine/RenderLib/Backend/RenderShaderPipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/RenderShaderPipeline.cpp.s
.PHONY : Engine/RenderLib/Backend/RenderShaderPipeline.cpp.s

Engine/RenderLib/Backend/Vulkan/VKBuffer.o: Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKBuffer.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.o

Engine/RenderLib/Backend/Vulkan/VKBuffer.i: Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKBuffer.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.i

Engine/RenderLib/Backend/Vulkan/VKBuffer.s: Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKBuffer.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKBuffer.cpp.s

Engine/RenderLib/Backend/Vulkan/VKContext.o: Engine/RenderLib/Backend/Vulkan/VKContext.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKContext.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKContext.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKContext.cpp.o

Engine/RenderLib/Backend/Vulkan/VKContext.i: Engine/RenderLib/Backend/Vulkan/VKContext.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKContext.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKContext.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKContext.cpp.i

Engine/RenderLib/Backend/Vulkan/VKContext.s: Engine/RenderLib/Backend/Vulkan/VKContext.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKContext.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKContext.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKContext.cpp.s

Engine/RenderLib/Backend/Vulkan/VKFramebuffer.o: Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKFramebuffer.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.o

Engine/RenderLib/Backend/Vulkan/VKFramebuffer.i: Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKFramebuffer.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.i

Engine/RenderLib/Backend/Vulkan/VKFramebuffer.s: Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKFramebuffer.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKFramebuffer.cpp.s

Engine/RenderLib/Backend/Vulkan/VKProgram.o: Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKProgram.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.o

Engine/RenderLib/Backend/Vulkan/VKProgram.i: Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKProgram.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.i

Engine/RenderLib/Backend/Vulkan/VKProgram.s: Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKProgram.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKProgram.cpp.s

Engine/RenderLib/Backend/Vulkan/VKShader.o: Engine/RenderLib/Backend/Vulkan/VKShader.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShader.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShader.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShader.cpp.o

Engine/RenderLib/Backend/Vulkan/VKShader.i: Engine/RenderLib/Backend/Vulkan/VKShader.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShader.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShader.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShader.cpp.i

Engine/RenderLib/Backend/Vulkan/VKShader.s: Engine/RenderLib/Backend/Vulkan/VKShader.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShader.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShader.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShader.cpp.s

Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.o: Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.o

Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.i: Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.i

Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.s: Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.cpp.s

Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.o: Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.o

Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.i: Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.i

Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.s: Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.cpp.s

Engine/RenderLib/Backend/Vulkan/VKTexture.o: Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKTexture.o

# target to build an object file
Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.o
.PHONY : Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.o

Engine/RenderLib/Backend/Vulkan/VKTexture.i: Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKTexture.i

# target to preprocess a source file
Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.i
.PHONY : Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.i

Engine/RenderLib/Backend/Vulkan/VKTexture.s: Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKTexture.s

# target to generate assembly for a file
Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.s
.PHONY : Engine/RenderLib/Backend/Vulkan/VKTexture.cpp.s

Engine/RenderLib/DrawBuffer.o: Engine/RenderLib/DrawBuffer.cpp.o
.PHONY : Engine/RenderLib/DrawBuffer.o

# target to build an object file
Engine/RenderLib/DrawBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/DrawBuffer.cpp.o
.PHONY : Engine/RenderLib/DrawBuffer.cpp.o

Engine/RenderLib/DrawBuffer.i: Engine/RenderLib/DrawBuffer.cpp.i
.PHONY : Engine/RenderLib/DrawBuffer.i

# target to preprocess a source file
Engine/RenderLib/DrawBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/DrawBuffer.cpp.i
.PHONY : Engine/RenderLib/DrawBuffer.cpp.i

Engine/RenderLib/DrawBuffer.s: Engine/RenderLib/DrawBuffer.cpp.s
.PHONY : Engine/RenderLib/DrawBuffer.s

# target to generate assembly for a file
Engine/RenderLib/DrawBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/DrawBuffer.cpp.s
.PHONY : Engine/RenderLib/DrawBuffer.cpp.s

Engine/RenderLib/RenderMain.o: Engine/RenderLib/RenderMain.cpp.o
.PHONY : Engine/RenderLib/RenderMain.o

# target to build an object file
Engine/RenderLib/RenderMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/RenderMain.cpp.o
.PHONY : Engine/RenderLib/RenderMain.cpp.o

Engine/RenderLib/RenderMain.i: Engine/RenderLib/RenderMain.cpp.i
.PHONY : Engine/RenderLib/RenderMain.i

# target to preprocess a source file
Engine/RenderLib/RenderMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/RenderMain.cpp.i
.PHONY : Engine/RenderLib/RenderMain.cpp.i

Engine/RenderLib/RenderMain.s: Engine/RenderLib/RenderMain.cpp.s
.PHONY : Engine/RenderLib/RenderMain.s

# target to generate assembly for a file
Engine/RenderLib/RenderMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/Engine/RenderLib/RenderMain.cpp.s
.PHONY : Engine/RenderLib/RenderMain.cpp.s

pngloader/lodepng.o: pngloader/lodepng.cpp.o
.PHONY : pngloader/lodepng.o

# target to build an object file
pngloader/lodepng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/pngloader/lodepng.cpp.o
.PHONY : pngloader/lodepng.cpp.o

pngloader/lodepng.i: pngloader/lodepng.cpp.i
.PHONY : pngloader/lodepng.i

# target to preprocess a source file
pngloader/lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/pngloader/lodepng.cpp.i
.PHONY : pngloader/lodepng.cpp.i

pngloader/lodepng.s: pngloader/lodepng.cpp.s
.PHONY : pngloader/lodepng.s

# target to generate assembly for a file
pngloader/lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SIREngineApplication.dir/build.make CMakeFiles/SIREngineApplication.dir/pngloader/lodepng.cpp.s
.PHONY : pngloader/lodepng.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... shaders"
	@echo "... SIREngineApplication"
	@echo "... Engine/Core/Application/GenericPlatform/GenericApplication.o"
	@echo "... Engine/Core/Application/GenericPlatform/GenericApplication.i"
	@echo "... Engine/Core/Application/GenericPlatform/GenericApplication.s"
	@echo "... Engine/Core/Application/Posix/PosixApplication.o"
	@echo "... Engine/Core/Application/Posix/PosixApplication.i"
	@echo "... Engine/Core/Application/Posix/PosixApplication.s"
	@echo "... Engine/Core/Application/Posix/PosixCrashHandler.o"
	@echo "... Engine/Core/Application/Posix/PosixCrashHandler.i"
	@echo "... Engine/Core/Application/Posix/PosixCrashHandler.s"
	@echo "... Engine/Core/ConsoleManager.o"
	@echo "... Engine/Core/ConsoleManager.i"
	@echo "... Engine/Core/ConsoleManager.s"
	@echo "... Engine/Core/Events/EventManager.o"
	@echo "... Engine/Core/Events/EventManager.i"
	@echo "... Engine/Core/Events/EventManager.s"
	@echo "... Engine/Core/Events/KeyEvent.o"
	@echo "... Engine/Core/Events/KeyEvent.i"
	@echo "... Engine/Core/Events/KeyEvent.s"
	@echo "... Engine/Core/FileSystem/FileCache.o"
	@echo "... Engine/Core/FileSystem/FileCache.i"
	@echo "... Engine/Core/FileSystem/FileCache.s"
	@echo "... Engine/Core/FileSystem/FileSystem.o"
	@echo "... Engine/Core/FileSystem/FileSystem.i"
	@echo "... Engine/Core/FileSystem/FileSystem.s"
	@echo "... Engine/Core/Input/InputManager.o"
	@echo "... Engine/Core/Input/InputManager.i"
	@echo "... Engine/Core/Input/InputManager.s"
	@echo "... Engine/Core/Logging/Logger.o"
	@echo "... Engine/Core/Logging/Logger.i"
	@echo "... Engine/Core/Logging/Logger.s"
	@echo "... Engine/Core/Serialization/Ini/IniReader.o"
	@echo "... Engine/Core/Serialization/Ini/IniReader.i"
	@echo "... Engine/Core/Serialization/Ini/IniReader.s"
	@echo "... Engine/Core/Serialization/Ini/IniWriter.o"
	@echo "... Engine/Core/Serialization/Ini/IniWriter.i"
	@echo "... Engine/Core/Serialization/Ini/IniWriter.s"
	@echo "... Engine/Core/Serialization/Ini/ini.o"
	@echo "... Engine/Core/Serialization/Ini/ini.i"
	@echo "... Engine/Core/Serialization/Ini/ini.s"
	@echo "... Engine/Core/Serialization/JSon/JsonCache.o"
	@echo "... Engine/Core/Serialization/JSon/JsonCache.i"
	@echo "... Engine/Core/Serialization/JSon/JsonCache.s"
	@echo "... Engine/Core/Serialization/TBon/TBonSerializer.o"
	@echo "... Engine/Core/Serialization/TBon/TBonSerializer.i"
	@echo "... Engine/Core/Serialization/TBon/TBonSerializer.s"
	@echo "... Engine/Core/SmMalloc/smmalloc.o"
	@echo "... Engine/Core/SmMalloc/smmalloc.i"
	@echo "... Engine/Core/SmMalloc/smmalloc.s"
	@echo "... Engine/Core/SmMalloc/smmalloc_generic.o"
	@echo "... Engine/Core/SmMalloc/smmalloc_generic.i"
	@echo "... Engine/Core/SmMalloc/smmalloc_generic.s"
	@echo "... Engine/Core/SmMalloc/smmalloc_tls.o"
	@echo "... Engine/Core/SmMalloc/smmalloc_tls.i"
	@echo "... Engine/Core/SmMalloc/smmalloc_tls.s"
	@echo "... Engine/Core/Util.o"
	@echo "... Engine/Core/Util.i"
	@echo "... Engine/Core/Util.s"
	@echo "... Engine/Memory/Allocators/SlabAllocator.o"
	@echo "... Engine/Memory/Allocators/SlabAllocator.i"
	@echo "... Engine/Memory/Allocators/SlabAllocator.s"
	@echo "... Engine/Memory/Allocators/VirtualStackAllocator.o"
	@echo "... Engine/Memory/Allocators/VirtualStackAllocator.i"
	@echo "... Engine/Memory/Allocators/VirtualStackAllocator.s"
	@echo "... Engine/Memory/Backend/TagArenaAllocator.o"
	@echo "... Engine/Memory/Backend/TagArenaAllocator.i"
	@echo "... Engine/Memory/Backend/TagArenaAllocator.s"
	@echo "... Engine/Memory/Memory.o"
	@echo "... Engine/Memory/Memory.i"
	@echo "... Engine/Memory/Memory.s"
	@echo "... Engine/RenderLib/Backend/ImageLib/LoadPNG.o"
	@echo "... Engine/RenderLib/Backend/ImageLib/LoadPNG.i"
	@echo "... Engine/RenderLib/Backend/ImageLib/LoadPNG.s"
	@echo "... Engine/RenderLib/Backend/ImageLoader.o"
	@echo "... Engine/RenderLib/Backend/ImageLoader.i"
	@echo "... Engine/RenderLib/Backend/ImageLoader.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLBuffer.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLBuffer.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLBuffer.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLContext.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLContext.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLContext.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLFramebuffer.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLFramebuffer.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLFramebuffer.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLProcs.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLProcs.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLProcs.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLProgram.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLProgram.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLProgram.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShader.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShader.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShader.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShaderBuffer.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLShaderPipeline.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLTexture.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLTexture.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLTexture.s"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLVertexArray.o"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLVertexArray.i"
	@echo "... Engine/RenderLib/Backend/OpenGL/GLVertexArray.s"
	@echo "... Engine/RenderLib/Backend/RenderContext.o"
	@echo "... Engine/RenderLib/Backend/RenderContext.i"
	@echo "... Engine/RenderLib/Backend/RenderContext.s"
	@echo "... Engine/RenderLib/Backend/RenderShaderPipeline.o"
	@echo "... Engine/RenderLib/Backend/RenderShaderPipeline.i"
	@echo "... Engine/RenderLib/Backend/RenderShaderPipeline.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKBuffer.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKBuffer.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKBuffer.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKContext.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKContext.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKContext.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKFramebuffer.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKFramebuffer.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKFramebuffer.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKProgram.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKProgram.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKProgram.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShader.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShader.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShader.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShaderBuffer.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKShaderPipeline.s"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKTexture.o"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKTexture.i"
	@echo "... Engine/RenderLib/Backend/Vulkan/VKTexture.s"
	@echo "... Engine/RenderLib/DrawBuffer.o"
	@echo "... Engine/RenderLib/DrawBuffer.i"
	@echo "... Engine/RenderLib/DrawBuffer.s"
	@echo "... Engine/RenderLib/RenderMain.o"
	@echo "... Engine/RenderLib/RenderMain.i"
	@echo "... Engine/RenderLib/RenderMain.s"
	@echo "... pngloader/lodepng.o"
	@echo "... pngloader/lodepng.i"
	@echo "... pngloader/lodepng.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

